export type ResumeRole =
  | "Software Engineer"
  | "Front End Developer"
  | "Back End Developer"
  | "Full Stack Developer"
  | "DevOps Engineer"
  | "Software Architect";

export const RESUME_ROLES: ResumeRole[] = [
  "Software Engineer",
  "Front End Developer",
  "Back End Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Software Architect",
];

export const ROLE_KEYWORDS: Record<ResumeRole, string[]> = {
  "Software Engineer": [], // Acts as "All" - shows everything
  "Front End Developer": [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind",
    "UI",
    "UX",
    "Frontend",
    "Web",
    "Redux",
    "Framer Motion",
    "Responsive",
    "Mobile",
    "Accessibility",
    "WCAG",
    "DOM",
    "Browser",
  ],
  "Back End Developer": [
    "Node.js",
    "Python",
    "API",
    "Database",
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "Backend",
    "Server",
    "Express",
    "NestJS",
    "Django",
    "FastAPI",
    "REST",
    "GraphQL",
    "Authentication",
    "Authorization",
    "Microservices",
  ],
  "Full Stack Developer": [
    "Full Stack",
    "Fullstack",
    "React",
    "Next.js",
    "Node.js",
    "TypeScript",
    "JavaScript",
    "Database",
    "API",
    "Frontend",
    "Backend",
    "Web",
    "Software",
    "Development",
    "Coding",
    "Programming",
    "Algorithm",
    "Data Structure",
    "Git",
    "Testing",
    "Debugging",
    "Agile",
    "Scrum",
  ],
  "DevOps Engineer": [
    "Docker",
    "Kubernetes",
    "CI/CD",
    "AWS",
    "Cloud",
    "Linux",
    "Bash",
    "DevOps",
    "Jenkins",
    "Terraform",
    "Ansible",
    "Infrastructure",
    "Monitoring",
    "Logging",
    "Pipeline",
    "Deployment",
    "Git",
  ],

  "Software Architect": [
    "Architecture",
    "System Design",
    "Scalability",
    "Microservices",
    "Patterns",
    "Cloud",
    "High Availability",
    "Security",
    "Performance",
    "Distributed Systems",
    "Integration",
  ],
};
